import { Clip, MediaItem, Track } from '../types/editor';

// Generated high-fidelity asset paths
export const STOCK_IMAGES = {
  neonCity: '/src/assets/images/stock_neon_city_1790320249691.jpg',
  natureDrone: '/src/assets/images/stock_nature_drone_1790320263022.jpg',
  studioInterview: '/src/assets/images/stock_studio_interview_1790320276622.jpg',
  abstractMotion: '/src/assets/images/stock_abstract_motion_1790320288922.jpg',
};

// Generate realistic audio waveform array (0 to 1 values)
function generateWaveform(length: number, intensity: number = 0.7): number[] {
  const wave: number[] = [];
  let current = 0.4;
  for (let i = 0; i < length; i++) {
    const change = (Math.random() - 0.48) * 0.3;
    current = Math.max(0.1, Math.min(0.95, current + change));
    // Add periodic rhythmic bursts
    const beat = i % 12 === 0 ? 0.35 : 0;
    wave.push(Math.min(1, current * intensity + beat));
  }
  return wave;
}

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'media-nature',
    name: 'A001_C004_Drone_Valley_4K.mov',
    type: 'video',
    url: STOCK_IMAGES.natureDrone,
    duration: 16.0,
    width: 3840,
    height: 2160,
    thumbnail: STOCK_IMAGES.natureDrone,
    generatorType: 'nature-drone',
  },
  {
    id: 'media-neon',
    name: 'A002_C012_Neon_Metropolis.mp4',
    type: 'video',
    url: STOCK_IMAGES.neonCity,
    duration: 12.0,
    width: 3840,
    height: 2160,
    thumbnail: STOCK_IMAGES.neonCity,
    generatorType: 'neon-city',
  },
  {
    id: 'media-interview',
    name: 'B001_C002_Interview_Take1.mov',
    type: 'video',
    url: STOCK_IMAGES.studioInterview,
    duration: 18.0,
    width: 1920,
    height: 1080,
    thumbnail: STOCK_IMAGES.studioInterview,
    generatorType: 'studio-interview',
  },
  {
    id: 'media-abstract',
    name: 'GFX_Motion_Ribbons_Loop.mp4',
    type: 'video',
    url: STOCK_IMAGES.abstractMotion,
    duration: 10.0,
    width: 1920,
    height: 1080,
    thumbnail: STOCK_IMAGES.abstractMotion,
    generatorType: 'abstract-motion',
  },
  {
    id: 'media-smpte',
    name: 'SMPTE_Color_Bars_Test.mov',
    type: 'generator',
    url: '',
    duration: 8.0,
    width: 1920,
    height: 1080,
    thumbnail: '',
    generatorType: 'smpte-bars',
  },
  {
    id: 'media-countdown',
    name: 'Universal_Countdown_Leader.mov',
    type: 'generator',
    url: '',
    duration: 5.0,
    width: 1920,
    height: 1080,
    thumbnail: '',
    generatorType: 'countdown',
  },
  {
    id: 'media-audio-bgm',
    name: 'Cinematic_Synth_Atmosphere_48k.wav',
    type: 'audio',
    url: '',
    duration: 32.0,
    thumbnail: '',
    audioTrackName: 'Cinematic Atmosphere Master',
    waveformData: generateWaveform(120, 0.8),
  },
  {
    id: 'media-audio-dialogue',
    name: 'Dialogue_Track_Director_Boom.wav',
    type: 'audio',
    url: '',
    duration: 20.0,
    thumbnail: '',
    audioTrackName: 'Director Commentary V1',
    waveformData: generateWaveform(90, 0.6),
  },
];

export const INITIAL_TRACKS: Track[] = [
  { id: 'v3', name: 'V3', type: 'video', height: 48, muted: false, solo: false, locked: false, visible: true, volume: 1, pan: 0 },
  { id: 'v2', name: 'V2', type: 'video', height: 48, muted: false, solo: false, locked: false, visible: true, volume: 1, pan: 0 },
  { id: 'v1', name: 'V1', type: 'video', height: 56, muted: false, solo: false, locked: false, visible: true, volume: 1, pan: 0 },
  { id: 'a1', name: 'A1', type: 'audio', height: 52, muted: false, solo: false, locked: false, visible: true, volume: 0.9, pan: 0 },
  { id: 'a2', name: 'A2', type: 'audio', height: 52, muted: false, solo: false, locked: false, visible: true, volume: 0.75, pan: 0 },
  { id: 'a3', name: 'A3', type: 'audio', height: 44, muted: false, solo: false, locked: false, visible: true, volume: 0.8, pan: 0 },
];

export const INITIAL_CLIPS: Clip[] = [
  // V1 (Main Track): Nature Drone -> Neon Metropolis -> Studio Interview
  {
    id: 'clip-1',
    trackId: 'v1',
    mediaId: 'media-nature',
    name: 'A001_Drone_Valley',
    type: 'video',
    startTime: 0.0,
    duration: 5.5,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#0284c7', // Sky Blue
    transform: { positionX: 0, positionY: 0, scale: 1.0, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: {
      exposure: 5,
      contrast: 15,
      highlights: -10,
      shadows: 10,
      temperature: 12,
      tint: -4,
      saturation: 110,
      vignette: 25,
      filmGrain: 10,
      lutPreset: 'warm-sunset',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'cross-dissolve', duration: 0.8 },
    transitionOut: { type: 'cross-dissolve', duration: 0.6 },
  },
  {
    id: 'clip-2',
    trackId: 'v1',
    mediaId: 'media-neon',
    name: 'A002_Neon_Metropolis',
    type: 'video',
    startTime: 5.5,
    duration: 6.0,
    trimStart: 1.0,
    speed: 1.0,
    colorTag: '#0284c7',
    transform: { positionX: 0, positionY: 0, scale: 1.05, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: {
      exposure: 8,
      contrast: 25,
      highlights: 10,
      shadows: -15,
      temperature: -18,
      tint: 14,
      saturation: 135,
      vignette: 35,
      filmGrain: 18,
      lutPreset: 'cyberpunk',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'cross-dissolve', duration: 0.6 },
    transitionOut: { type: 'dip-to-black', duration: 0.5 },
  },
  {
    id: 'clip-3',
    trackId: 'v1',
    mediaId: 'media-interview',
    name: 'B001_Interview_Take1',
    type: 'video',
    startTime: 11.5,
    duration: 6.5,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#0284c7',
    transform: { positionX: 0, positionY: 0, scale: 1.0, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: {
      exposure: 0,
      contrast: 10,
      highlights: -5,
      shadows: 5,
      temperature: 8,
      tint: 2,
      saturation: 105,
      vignette: 20,
      filmGrain: 12,
      lutPreset: 'teal-orange',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'dip-to-black', duration: 0.5 },
    transitionOut: { type: 'cross-dissolve', duration: 0.8 },
  },

  // V2 (B-Roll / Cutaway / Overlay)
  {
    id: 'clip-4',
    trackId: 'v2',
    mediaId: 'media-abstract',
    name: 'GFX_Motion_Ribbons',
    type: 'video',
    startTime: 7.0,
    duration: 3.5,
    trimStart: 0.0,
    speed: 1.2,
    colorTag: '#7c3aed', // Purple
    transform: { positionX: 280, positionY: -140, scale: 0.42, rotation: -3, opacity: 0.92, blendMode: 'screen' },
    colorGrading: {
      exposure: 15,
      contrast: 20,
      highlights: 10,
      shadows: 0,
      temperature: -10,
      tint: 20,
      saturation: 140,
      vignette: 0,
      filmGrain: 0,
      lutPreset: 'cyberpunk',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: true },
    audioSettings: { volume: -6, pan: 0.3, mute: false },
    transitionIn: { type: 'fade', duration: 0.4 },
    transitionOut: { type: 'fade', duration: 0.4 },
  },

  // V3 (Titles & Lower Thirds)
  {
    id: 'clip-5',
    trackId: 'v3',
    mediaId: 'title-intro',
    name: 'TITLE: CINEMATIC REVEAL',
    type: 'title',
    startTime: 0.8,
    duration: 4.2,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#d97706', // Amber/Orange
    transform: { positionX: 0, positionY: 0, scale: 1.0, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: {
      exposure: 0,
      contrast: 0,
      highlights: 0,
      shadows: 0,
      temperature: 0,
      tint: 0,
      saturation: 100,
      vignette: 0,
      filmGrain: 0,
      lutPreset: 'none',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    titleSettings: {
      text: 'CHRONICLES OF HORIZON',
      subtext: 'A CINEMATIC DIRECTORIAL SEQUENCE · 4K UHD',
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 38,
      color: '#ffffff',
      strokeColor: '#000000',
      strokeWidth: 2,
      backgroundColor: 'rgba(0,0,0,0.6)',
      hasBackground: false,
      alignment: 'center',
      presetStyle: 'cinematic-title',
    },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'fade', duration: 0.8 },
    transitionOut: { type: 'fade', duration: 0.8 },
  },
  {
    id: 'clip-6',
    trackId: 'v3',
    mediaId: 'title-lower-third',
    name: 'LOWER_THIRD: Director Interview',
    type: 'title',
    startTime: 12.0,
    duration: 4.5,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#d97706',
    transform: { positionX: 0, positionY: 260, scale: 1.0, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: {
      exposure: 0,
      contrast: 0,
      highlights: 0,
      shadows: 0,
      temperature: 0,
      tint: 0,
      saturation: 100,
      vignette: 0,
      filmGrain: 0,
      lutPreset: 'none',
    },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    titleSettings: {
      text: 'ELENA VANCE',
      subtext: 'Executive Director & Cinematographer · Visionary Pictures',
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 22,
      color: '#ffffff',
      strokeColor: '#000000',
      strokeWidth: 0,
      backgroundColor: 'rgba(15, 23, 42, 0.85)',
      hasBackground: true,
      alignment: 'left',
      presetStyle: 'lower-third',
    },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'wipe-left', duration: 0.5 },
    transitionOut: { type: 'fade', duration: 0.5 },
  },

  // Audio Tracks (A1 & A2)
  {
    id: 'clip-7',
    trackId: 'a1',
    mediaId: 'media-audio-bgm',
    name: 'Atmosphere_BGM_Master.wav',
    type: 'audio',
    startTime: 0.0,
    duration: 18.0,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#059669', // Emerald Green
    transform: { positionX: 0, positionY: 0, scale: 1, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: { exposure: 0, contrast: 0, highlights: 0, shadows: 0, temperature: 0, tint: 0, saturation: 100, vignette: 0, filmGrain: 0, lutPreset: 'none' },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    audioSettings: { volume: 0, pan: 0, mute: false },
    transitionIn: { type: 'fade', duration: 1.0 },
    transitionOut: { type: 'fade', duration: 1.2 },
  },
  {
    id: 'clip-8',
    trackId: 'a2',
    mediaId: 'media-audio-dialogue',
    name: 'Dialogue_Interview_Boom.wav',
    type: 'audio',
    startTime: 11.8,
    duration: 6.0,
    trimStart: 0.0,
    speed: 1.0,
    colorTag: '#059669',
    transform: { positionX: 0, positionY: 0, scale: 1, rotation: 0, opacity: 1, blendMode: 'normal' },
    colorGrading: { exposure: 0, contrast: 0, highlights: 0, shadows: 0, temperature: 0, tint: 0, saturation: 100, vignette: 0, filmGrain: 0, lutPreset: 'none' },
    effects: { gaussianBlur: 0, glitch: false, mirror: false, invert: false, blackAndWhite: false, edgeGlow: false },
    audioSettings: { volume: +2, pan: 0, mute: false },
    transitionIn: { type: 'fade', duration: 0.3 },
    transitionOut: { type: 'fade', duration: 0.4 },
  },
];
